### ISSUE TITLE
Relocate or change reference to amuse framework

### ISSUE THREAD

**Issue by Maartenvm** [eWaterCycle/HyMUSE#9]
Currently the Ansible script installs the Amuse framework from Inti's personal github repo (https://github.com/ipelupessy/amuse-framework.git). 

We should make a copy of Amuse framework (so we can pin the version number for releases).

Link to the Ansible script line:
https://github.com/eWaterCycle/infra/blob/3128d4d0932ad9026e81940757e395903c423b0b/launcher/playbook.yml#L262

**Comment by ipelupessy** [comment]
forked the amuse framework repo at eWaterCycle
